version: 0.2

phases:
  install:
    # Getting the integration code from usetrace universal-integration repository
    commands:
      - git clone https://github.com/usetrace/universal-integration.git
      - npm install --prefix universal-integration
  
  build:
    commands:
      # Trigger single trace job (replace with actual commands)
      - echo "Trigger single trace job"
      
      # Passing some parameters as env vars
      - export INPUT_BUILD_TIMEOUT_SECONDS=900
      - export INPUT_FAIL_ON_FAILED_TRACES=false
      
      # Parameters can be passed by the command line too. These has precedence over env var ones
      - npm run usetrace -- --traceId {Trace Id} --browsers chrome,firefox --prefix universal-integration

      # Process entire project results
      - |
        if [ $(jq '.report.failures | length' output.json) -eq 0 ]; then
          echo "Everything was good"
        else
          echo "Something is not right. Perform corrective actions here"
        fi

      # Process single trace artifact
      - |
        cat output.json | jq '.status'
        cat output.json

      # Process entire project results
      - |
        cat output.json | jq '.report.failures'
        if [ $(jq '.report.failures | length' output.json) -eq 0 ]; then
          echo "MOCK: exit 0"
          # exit 0
        else
          echo "MOCK: exit 1"
         # exit 1
        fi

  post_build:
    # Conditional actions based on exit code
    commands:
      - echo "All traces passed!"  # Success message (exit code 0)
      - |
          if [ $? -eq 0 ]; then
            # Need to find equivalent output message here.
            - echo "You are lucky!"
          else
            echo "No good news... Taking appropriate actions..."
          fi
