version: 0.2

phases:
  install:
    commands:
      # - yum install jq  # Install jq for JSON processing
      # jp seems to be already installed
      - echo "phase install"

  pre_build:
    # Logic for including templates would be implemented here
    commands:
      - echo "Magic required here"

  build:
    commands:
      # Trigger single trace job (replace with actual commands)
      - echo "Trigger single trace job"
      
      # Trigger the entire project job (replace with actual commands)
      - echo "Trigger project trace job. Can we use conditionals?"
      - git clone https://github.com/usetrace/universal-integration.git
      - npm install --prefix universal-integration
      - ls
      # You can set some values by env vars directly
      - export INPUT_BUILD_TIMEOUT_SECONDS=10
      - export INPUT_FAIL_ON_FAILED_TRACES=false
      # Parameters can be passed by the command line too. These has precedence over env var ones
      - npm run usetrace -- --traceId Zux6zjrzOwAYPAJK_cLMvZ3_xVspdHDW --browsers chrome,firefox --buildTimeoutSeconds 900 --webhookUrl https://webhook-test.com/yourWebhookId --parameters '"key1":"value1", "key2":"value2"' --prefix universal-integration
      - ls
      # Process single trace artifact
      - |
        cat output.json | jq '.status'
        cat output.json

      # Process entire project results
      - |
        cat output.json | jq '.report.failures'
        if [ $(jq '.report.failures | length' output.json) -eq 0 ]; then
          echo "MOCK: exit 0"
          # exit 0
        else
          echo "MOCK: exit 1"
         # exit 1
        fi

  post_build:
    # Conditional actions based on exit code
    commands:
      - echo "All traces passed!"  # Success message (exit code 0)
      - |
          if [ $? -eq 0 ]; then
            # Need to find equivalent output message here.
            - echo "You are lucky!"
          else
            echo "No good news... Taking appropriate actions..."
          fi
